# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/Garnet/Desktop/Python/Decline Analysis/Version 1/Code V1.0/mainwindow_multisegment.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from segmentwindow import ParameterFrame

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1116, 547)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.treeWidget, 0, 0, 10, 1)
        self.plotWidget = MplWidget(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setObjectName("plotWidget")
        self.gridLayout.addWidget(self.plotWidget, 0, 1, 5, 14)

        self.ParameterFrame = ParameterFrame(self)
        self.ParameterFrame.setObjectName("ParameterFrame")

        self.gridLayout.addWidget(self.ParameterFrame, 6, 1, 4, 11)

        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.BestFitFromSelectionUI = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BestFitFromSelectionUI.sizePolicy().hasHeightForWidth())
        self.BestFitFromSelectionUI.setSizePolicy(sizePolicy)
        self.BestFitFromSelectionUI.setObjectName("BestFitFromSelectionUI")
        self.gridLayout_4.addWidget(self.BestFitFromSelectionUI, 0, 0, 1, 1)
        self.ExportToExcelUI = QtWidgets.QPushButton(self.frame)
        self.ExportToExcelUI.setObjectName("ExportToExcelUI")
        self.gridLayout_4.addWidget(self.ExportToExcelUI, 1, 0, 1, 1)
        self.UnitsUI = QtWidgets.QPushButton(self.frame)
        self.UnitsUI.setObjectName("UnitsUI")
        self.gridLayout_4.addWidget(self.UnitsUI, 2, 0, 1, 1)
        self.PlotUI = QtWidgets.QPushButton(self.frame)
        self.PlotUI.setObjectName("PlotUI")
        self.gridLayout_4.addWidget(self.PlotUI, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 6, 12, 4, 3)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1116, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menuBar)
        self.menuTools.setObjectName("menuTools")
        self.menuChange_Units = QtWidgets.QMenu(self.menuTools)
        self.menuChange_Units.setObjectName("menuChange_Units")
        self.menuChange_Plot = QtWidgets.QMenu(self.menuTools)
        self.menuChange_Plot.setObjectName("menuChange_Plot")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionImport_From_Excel = QtWidgets.QAction(MainWindow)
        self.actionImport_From_Excel.setObjectName("actionImport_From_Excel")
        self.actionProject_Constraints = QtWidgets.QAction(MainWindow)
        self.actionProject_Constraints.setObjectName("actionProject_Constraints")
        self.actionConstrain_Well = QtWidgets.QAction(MainWindow)
        self.actionConstrain_Well.setObjectName("actionConstrain_Well")
        self.actionNew_Project_2 = QtWidgets.QAction(MainWindow)
        self.actionNew_Project_2.setObjectName("actionNew_Project_2")
        self.actionExport_Project_to_Excel = QtWidgets.QAction(MainWindow)
        self.actionExport_Project_to_Excel.setObjectName("actionExport_Project_to_Excel")
        self.actionExport_Well_to_Excel = QtWidgets.QAction(MainWindow)
        self.actionExport_Well_to_Excel.setObjectName("actionExport_Well_to_Excel")
        self.actionExport_EUR_to_Excel = QtWidgets.QAction(MainWindow)
        self.actionExport_EUR_to_Excel.setObjectName("actionExport_EUR_to_Excel")
        self.actionExport_Project_EUR_to_Excel = QtWidgets.QAction(MainWindow)
        self.actionExport_Project_EUR_to_Excel.setObjectName("actionExport_Project_EUR_to_Excel")
        self.actionMetric = QtWidgets.QAction(MainWindow)
        self.actionMetric.setObjectName("actionMetric")
        self.actionImperial = QtWidgets.QAction(MainWindow)
        self.actionImperial.setObjectName("actionImperial")
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionSave_File = QtWidgets.QAction(MainWindow)
        self.actionSave_File.setObjectName("actionSave_File")
        self.actionSave_File_As = QtWidgets.QAction(MainWindow)
        self.actionSave_File_As.setObjectName("actionSave_File_As")
        self.actionScatter = QtWidgets.QAction(MainWindow)
        self.actionScatter.setObjectName("actionScatter")
        self.actionLine = QtWidgets.QAction(MainWindow)
        self.actionLine.setObjectName("actionLine")
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_File)
        self.menuFile.addAction(self.actionSave_File_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport_From_Excel)
        self.menuChange_Units.addAction(self.actionMetric)
        self.menuChange_Units.addAction(self.actionImperial)
        self.menuChange_Plot.addAction(self.actionScatter)
        self.menuChange_Plot.addAction(self.actionLine)
        self.menuTools.addAction(self.menuChange_Units.menuAction())
        self.menuTools.addAction(self.actionProject_Constraints)
        self.menuTools.addAction(self.actionConstrain_Well)
        self.menuTools.addAction(self.menuChange_Plot.menuAction())
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BestFitFromSelectionUI.setText(_translate("MainWindow", "Best Fit from Selection"))
        self.ExportToExcelUI.setText(_translate("MainWindow", "Export To Excel"))
        self.UnitsUI.setText(_translate("MainWindow", "Toggle Units"))
        self.PlotUI.setText(_translate("MainWindow", "Toggle Plot"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuChange_Units.setTitle(_translate("MainWindow", "Change Units"))
        self.menuChange_Plot.setTitle(_translate("MainWindow", "Plot Type"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionImport_From_Excel.setText(_translate("MainWindow", "Import from Excel"))
        self.actionProject_Constraints.setText(_translate("MainWindow", "Project Constraints"))
        self.actionConstrain_Well.setText(_translate("MainWindow", "Constrain Well"))
        self.actionNew_Project_2.setText(_translate("MainWindow", "New Project"))
        self.actionExport_Project_to_Excel.setText(_translate("MainWindow", "Export Project to Excel"))
        self.actionExport_Well_to_Excel.setText(_translate("MainWindow", "Export Well to Excel"))
        self.actionExport_EUR_to_Excel.setText(_translate("MainWindow", "Export Well EUR to Excel"))
        self.actionExport_Project_EUR_to_Excel.setText(_translate("MainWindow", "Export Project EUR to Excel"))
        self.actionMetric.setText(_translate("MainWindow", "Metric"))
        self.actionImperial.setText(_translate("MainWindow", "Imperial"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open"))
        self.actionSave_File.setText(_translate("MainWindow", "Save"))
        self.actionSave_File_As.setText(_translate("MainWindow", "Save As"))
        self.actionScatter.setText(_translate("MainWindow", "Scatter Plot"))
        self.actionLine.setText(_translate("MainWindow", "Line Plot"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

